pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        SONAR_TOKEN = credentials('E_stack') // Better to use Jenkins credentials
        SONARQUBE_SERVER = 'http://localhost:9000/'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ER-RAJY/E-stack.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('E_stack') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') { // This requires SonarQube Scanner plugin
                    dir('E_stack') {
                        bat "mvn sonar:sonar " +
                            "-Dsonar.projectKey=E_stack " +
                            "-Dsonar.host.url=${SONARQUBE_SERVER} " +
                            "-Dsonar.login=${SONAR_TOKEN}"
                    }
                }
            }
        }
    }
}