pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        SONAR_CREDS = credentials('E-stack') // Using the exact credential ID you created
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ER-RAJY/E-stack.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('E_stack') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') { // Match this name with your Jenkins SonarQube installation name
                    dir('E_stack') {
                        bat """
                            mvn sonar:sonar \
                            -Dsonar.projectKey=E_stack \
                            -Dsonar.host.url=http://localhost:9000 \
                            -Dsonar.token=%SONAR_CREDS_PSW%
                        """
                    }
                }
            }
        }
    }
}