pipeline {
    agent any
    tools {
        maven 'mvn'
    }
    environment {
        SONAR_TOKEN = 'squ_03903e1dd5dc823904fb799fb49151070c313c02'
        SONARQUBE_SERVER = 'http://localhost:9000/'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ER-RAJY/E-stack.git'
            }
        }
        stage('Build & Test') {
            steps {
                withMaven(maven: 'mvn') {
                    bat 'mvn clean install'
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'Sonar'
                    bat "${scannerHome}/bin/sonar-scanner " +
                        "-Dsonar.projectKey=E_stack " + // Fixed project key
                        "-Dsonar.sources=. " +
                        "-Dsonar.host.url=${SONARQUBE_SERVER} " +
                        "-Dsonar.login=${SONAR_TOKEN} " + // Fixed variable name
                        "-Dsonar.java.binaries=target/classes"
                }
            }
        }
    }
}
